version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cnab-postgres
    restart: always
    environment:
      POSTGRES_USER: cnabuser
      POSTGRES_PASSWORD: cnabpass
      POSTGRES_DB: cnabdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build: ./backend
    container_name: cnab-backend
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://cnabuser:cnabpass@db:5432/cnabdb

volumes:
  pgdata: